# 서비스마다 달라지는 값
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/notify_db?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 편의를 위해 update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: "optional:file:.env.local[.properties]"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

kafka:
  consumer:
    following-group:
      bootstrap-servers: kafka:9092
      group-id: following-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    chatting-group:
      bootstrap-servers: kafka:9092
      group-id: chatting-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    comment-group:
      bootstrap-servers: kafka:9092
      group-id: comment-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    like-group:
      bootstrap-servers: kafka:9092
      group-id: like-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


redis:
  token:
    host: token-redis
    port: 6379
    password: ${REDIS_PASSWORD}


jwt:
  secretKey: ${JWT_KEY}
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

