# 서비스마다 달라지는 값
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/board_db?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update   # 개발 편의를 위해 update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: "optional:file:.env.local[.properties]"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

kafka:
  admin:
    properties:
      bootstrap.servers: kafka:9092
  topic-config:
    comment:
      name: comment-topic
      partitions: 3
      replicas: 1
    like:
      name: like-topic
      partitions: 3
      replicas: 1

  producer:
    bootstrap-servers: kafka:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    retries: 2

  consumer:
    following-group:
      bootstrap-servers: kafka:9092
      group-id: following-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    favorites-group:
      bootstrap-servers: kafka:9092
      group-id: favorites-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

redis:
  token:
    host: token-redis
    port: 6379
    password: ${REDIS_PASSWORD}

jwt:
  secretKey: ${JWT_KEY}
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

cloud:
  aws:
    s3:
      bucket:
        name: whisky-board-image
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    enabled: true


feign:
  client:
    config:
      user-service:
        connectTimeout: 1000 # 연결을 시도할 최대 시간 (ms) - 1초
        readTimeout: 1000